/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.12.1.454 */
/* Module Version: 5.8 */
/* C:\lscc\diamond\3.12\ispfpga\bin\nt64\scuba.exe -w -n fifo -lang verilog -synth lse -bus_exp 7 -bb -arch xo3c00f -type ebfifo -depth 4096 -width 32 -rwidth 8 -no_enable -pe 10 -pf 4085  */
/* Sat Jul 16 00:15:15 2022 */


`timescale 1 ns / 1 ps
module fifo (Data, WrClock, RdClock, WrEn, RdEn, Reset, RPReset, Q, 
    Empty, Full, AlmostEmpty, AlmostFull)/* synthesis NGD_DRC_MASK=1 */;
    input wire [31:0] Data;
    input wire WrClock;
    input wire RdClock;
    input wire WrEn;
    input wire RdEn;
    input wire Reset;
    input wire RPReset;
    output wire [7:0] Q;
    output wire Empty;
    output wire Full;
    output wire AlmostEmpty;
    output wire AlmostFull;

    wire Full_int_inv;
    wire Empty_int_inv;
    wire fifo_pf0;
    wire fifo_pe0;
    wire fifo_f0;
    wire fifo_e0;
    wire fifo_pf1;
    wire fifo_pe1;
    wire fifo_f1;
    wire fifo_e1;
    wire Empty_int;
    wire Full_int;
    wire fifo_fwe1;
    wire fifo_wei;
    wire fifo_fwe0;
    wire rfifo_rei_tg;
    wire fifo_fre0;
    wire rRst;
    wire fifo_rei;
    wire fifo_fre1;
    wire scuba_vlo;
    wire scuba_vhi;
    wire ififo_reiring0;
    wire ififo_reiring1;
    wire co0;
    wire fifo_reirs_ci;
    wire fifo_reiring0;
    wire fifo_reiring1;
    wire Q_m1;
    wire Q_m0;
    wire Q_1_m1;
    wire Q_1_m0;
    wire Q_2_m1;
    wire Q_2_m0;
    wire Q_3_m1;
    wire Q_3_m0;
    wire Q_4_m1;
    wire Q_4_m0;
    wire Q_5_m1;
    wire Q_5_m0;
    wire Q_6_m1;
    wire Q_6_m0;
    wire fiforsel;
    wire Q_7_m1;
    wire Q_7_m0;

    INV INV_1 (.A(Full_int), .Z(Full_int_inv));

    AND2 AND2_t1 (.A(WrEn), .B(Full_int_inv), .Z(fifo_wei));

    INV INV_0 (.A(Empty_int), .Z(Empty_int_inv));

    AND2 AND2_t0 (.A(RdEn), .B(Empty_int_inv), .Z(fifo_rei));

    defparam LUT4_5.initval =  16'h8000 ;
    ROM16X1A LUT4_5 (.AD3(fifo_reiring0), .AD2(fifo_reiring1), .AD1(fifo_rei), 
        .AD0(scuba_vhi), .DO0(rfifo_rei_tg));

    defparam LUT4_4.initval =  16'hfffe ;
    ROM16X1A LUT4_4 (.AD3(Reset), .AD2(RPReset), .AD1(scuba_vlo), .AD0(scuba_vlo), 
        .DO0(rRst));

    defparam LUT4_3.initval =  16'h8000 ;
    ROM16X1A LUT4_3 (.AD3(fifo_e0), .AD2(fifo_e1), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(Empty_int));

    defparam LUT4_2.initval =  16'h8000 ;
    ROM16X1A LUT4_2 (.AD3(fifo_f0), .AD2(fifo_f1), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(Full_int));

    defparam LUT4_1.initval =  16'h8000 ;
    ROM16X1A LUT4_1 (.AD3(fifo_pe0), .AD2(fifo_pe1), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(AlmostEmpty));

    defparam LUT4_0.initval =  16'h8000 ;
    ROM16X1A LUT4_0 (.AD3(fifo_pf0), .AD2(fifo_pf1), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(AlmostFull));

    defparam fifo_0_15.FULLPOINTER1 = "0b01111111111100" ;
    defparam fifo_0_15.FULLPOINTER = "0b10000000000000" ;
    defparam fifo_0_15.AFPOINTER1 = "0b01111111100100" ;
    defparam fifo_0_15.AFPOINTER = "0b01111111101000" ;
    defparam fifo_0_15.AEPOINTER1 = "0b00000000000110" ;
    defparam fifo_0_15.AEPOINTER = "0b00000000000101" ;
    defparam fifo_0_15.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_0_15.GSR = "DISABLED" ;
    defparam fifo_0_15.RESETMODE = "ASYNC" ;
    defparam fifo_0_15.REGMODE = "NOREG" ;
    defparam fifo_0_15.CSDECODE_R = "0b11" ;
    defparam fifo_0_15.CSDECODE_W = "0b11" ;
    defparam fifo_0_15.DATA_WIDTH_R = 1 ;
    defparam fifo_0_15.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_0_15 (.DI0(Data[0]), .DI1(Data[8]), .DI2(Data[16]), .DI3(Data[24]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(fifo_e0), 
        .AEF(fifo_pe0), .AFF(fifo_pf0), .FF(fifo_f0));

    defparam fifo_1_14.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_14.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_1_14.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_14.AFPOINTER = "0b11111111111111" ;
    defparam fifo_1_14.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_14.AEPOINTER = "0b11111111111111" ;
    defparam fifo_1_14.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_1_14.GSR = "DISABLED" ;
    defparam fifo_1_14.RESETMODE = "ASYNC" ;
    defparam fifo_1_14.REGMODE = "NOREG" ;
    defparam fifo_1_14.CSDECODE_R = "0b11" ;
    defparam fifo_1_14.CSDECODE_W = "0b11" ;
    defparam fifo_1_14.DATA_WIDTH_R = 1 ;
    defparam fifo_1_14.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_1_14 (.DI0(Data[1]), .DI1(Data[9]), .DI2(Data[17]), .DI3(Data[25]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_1_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_2_13.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_13.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_2_13.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_13.AFPOINTER = "0b11111111111111" ;
    defparam fifo_2_13.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_13.AEPOINTER = "0b11111111111111" ;
    defparam fifo_2_13.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_2_13.GSR = "DISABLED" ;
    defparam fifo_2_13.RESETMODE = "ASYNC" ;
    defparam fifo_2_13.REGMODE = "NOREG" ;
    defparam fifo_2_13.CSDECODE_R = "0b11" ;
    defparam fifo_2_13.CSDECODE_W = "0b11" ;
    defparam fifo_2_13.DATA_WIDTH_R = 1 ;
    defparam fifo_2_13.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_2_13 (.DI0(Data[2]), .DI1(Data[10]), .DI2(Data[18]), .DI3(Data[26]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_2_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_3_12.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_12.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_3_12.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_12.AFPOINTER = "0b11111111111111" ;
    defparam fifo_3_12.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_12.AEPOINTER = "0b11111111111111" ;
    defparam fifo_3_12.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_3_12.GSR = "DISABLED" ;
    defparam fifo_3_12.RESETMODE = "ASYNC" ;
    defparam fifo_3_12.REGMODE = "NOREG" ;
    defparam fifo_3_12.CSDECODE_R = "0b11" ;
    defparam fifo_3_12.CSDECODE_W = "0b11" ;
    defparam fifo_3_12.DATA_WIDTH_R = 1 ;
    defparam fifo_3_12.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_3_12 (.DI0(Data[3]), .DI1(Data[11]), .DI2(Data[19]), .DI3(Data[27]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_3_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_4_11.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_4_11.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_4_11.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_4_11.AFPOINTER = "0b11111111111111" ;
    defparam fifo_4_11.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_4_11.AEPOINTER = "0b11111111111111" ;
    defparam fifo_4_11.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_4_11.GSR = "DISABLED" ;
    defparam fifo_4_11.RESETMODE = "ASYNC" ;
    defparam fifo_4_11.REGMODE = "NOREG" ;
    defparam fifo_4_11.CSDECODE_R = "0b11" ;
    defparam fifo_4_11.CSDECODE_W = "0b11" ;
    defparam fifo_4_11.DATA_WIDTH_R = 1 ;
    defparam fifo_4_11.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_4_11 (.DI0(Data[4]), .DI1(Data[12]), .DI2(Data[20]), .DI3(Data[28]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_4_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_5_10.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_5_10.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_5_10.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_5_10.AFPOINTER = "0b11111111111111" ;
    defparam fifo_5_10.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_5_10.AEPOINTER = "0b11111111111111" ;
    defparam fifo_5_10.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_5_10.GSR = "DISABLED" ;
    defparam fifo_5_10.RESETMODE = "ASYNC" ;
    defparam fifo_5_10.REGMODE = "NOREG" ;
    defparam fifo_5_10.CSDECODE_R = "0b11" ;
    defparam fifo_5_10.CSDECODE_W = "0b11" ;
    defparam fifo_5_10.DATA_WIDTH_R = 1 ;
    defparam fifo_5_10.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_5_10 (.DI0(Data[5]), .DI1(Data[13]), .DI2(Data[21]), .DI3(Data[29]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_5_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_6_9.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_6_9.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_6_9.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_6_9.AFPOINTER = "0b11111111111111" ;
    defparam fifo_6_9.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_6_9.AEPOINTER = "0b11111111111111" ;
    defparam fifo_6_9.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_6_9.GSR = "DISABLED" ;
    defparam fifo_6_9.RESETMODE = "ASYNC" ;
    defparam fifo_6_9.REGMODE = "NOREG" ;
    defparam fifo_6_9.CSDECODE_R = "0b11" ;
    defparam fifo_6_9.CSDECODE_W = "0b11" ;
    defparam fifo_6_9.DATA_WIDTH_R = 1 ;
    defparam fifo_6_9.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_6_9 (.DI0(Data[6]), .DI1(Data[14]), .DI2(Data[22]), .DI3(Data[30]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_6_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_7_8.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_7_8.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_7_8.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_7_8.AFPOINTER = "0b11111111111111" ;
    defparam fifo_7_8.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_7_8.AEPOINTER = "0b11111111111111" ;
    defparam fifo_7_8.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_7_8.GSR = "DISABLED" ;
    defparam fifo_7_8.RESETMODE = "ASYNC" ;
    defparam fifo_7_8.REGMODE = "NOREG" ;
    defparam fifo_7_8.CSDECODE_R = "0b11" ;
    defparam fifo_7_8.CSDECODE_W = "0b11" ;
    defparam fifo_7_8.DATA_WIDTH_R = 1 ;
    defparam fifo_7_8.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_7_8 (.DI0(Data[7]), .DI1(Data[15]), .DI2(Data[23]), .DI3(Data[31]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe0), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre0), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_7_m0), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_0_7.FULLPOINTER1 = "0b01111111111100" ;
    defparam fifo_0_7.FULLPOINTER = "0b10000000000000" ;
    defparam fifo_0_7.AFPOINTER1 = "0b01111111100100" ;
    defparam fifo_0_7.AFPOINTER = "0b01111111101000" ;
    defparam fifo_0_7.AEPOINTER1 = "0b00000000000110" ;
    defparam fifo_0_7.AEPOINTER = "0b00000000000101" ;
    defparam fifo_0_7.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_0_7.GSR = "DISABLED" ;
    defparam fifo_0_7.RESETMODE = "ASYNC" ;
    defparam fifo_0_7.REGMODE = "NOREG" ;
    defparam fifo_0_7.CSDECODE_R = "0b11" ;
    defparam fifo_0_7.CSDECODE_W = "0b11" ;
    defparam fifo_0_7.DATA_WIDTH_R = 1 ;
    defparam fifo_0_7.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_0_7 (.DI0(Data[0]), .DI1(Data[8]), .DI2(Data[16]), .DI3(Data[24]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(fifo_e1), 
        .AEF(fifo_pe1), .AFF(fifo_pf1), .FF(fifo_f1));

    defparam fifo_1_6.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_6.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_1_6.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_6.AFPOINTER = "0b11111111111111" ;
    defparam fifo_1_6.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_1_6.AEPOINTER = "0b11111111111111" ;
    defparam fifo_1_6.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_1_6.GSR = "DISABLED" ;
    defparam fifo_1_6.RESETMODE = "ASYNC" ;
    defparam fifo_1_6.REGMODE = "NOREG" ;
    defparam fifo_1_6.CSDECODE_R = "0b11" ;
    defparam fifo_1_6.CSDECODE_W = "0b11" ;
    defparam fifo_1_6.DATA_WIDTH_R = 1 ;
    defparam fifo_1_6.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_1_6 (.DI0(Data[1]), .DI1(Data[9]), .DI2(Data[17]), .DI3(Data[25]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_1_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_2_5.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_5.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_2_5.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_5.AFPOINTER = "0b11111111111111" ;
    defparam fifo_2_5.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_2_5.AEPOINTER = "0b11111111111111" ;
    defparam fifo_2_5.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_2_5.GSR = "DISABLED" ;
    defparam fifo_2_5.RESETMODE = "ASYNC" ;
    defparam fifo_2_5.REGMODE = "NOREG" ;
    defparam fifo_2_5.CSDECODE_R = "0b11" ;
    defparam fifo_2_5.CSDECODE_W = "0b11" ;
    defparam fifo_2_5.DATA_WIDTH_R = 1 ;
    defparam fifo_2_5.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_2_5 (.DI0(Data[2]), .DI1(Data[10]), .DI2(Data[18]), .DI3(Data[26]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_2_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_3_4.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_4.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_3_4.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_4.AFPOINTER = "0b11111111111111" ;
    defparam fifo_3_4.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_3_4.AEPOINTER = "0b11111111111111" ;
    defparam fifo_3_4.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_3_4.GSR = "DISABLED" ;
    defparam fifo_3_4.RESETMODE = "ASYNC" ;
    defparam fifo_3_4.REGMODE = "NOREG" ;
    defparam fifo_3_4.CSDECODE_R = "0b11" ;
    defparam fifo_3_4.CSDECODE_W = "0b11" ;
    defparam fifo_3_4.DATA_WIDTH_R = 1 ;
    defparam fifo_3_4.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_3_4 (.DI0(Data[3]), .DI1(Data[11]), .DI2(Data[19]), .DI3(Data[27]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_3_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_4_3.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_4_3.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_4_3.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_4_3.AFPOINTER = "0b11111111111111" ;
    defparam fifo_4_3.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_4_3.AEPOINTER = "0b11111111111111" ;
    defparam fifo_4_3.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_4_3.GSR = "DISABLED" ;
    defparam fifo_4_3.RESETMODE = "ASYNC" ;
    defparam fifo_4_3.REGMODE = "NOREG" ;
    defparam fifo_4_3.CSDECODE_R = "0b11" ;
    defparam fifo_4_3.CSDECODE_W = "0b11" ;
    defparam fifo_4_3.DATA_WIDTH_R = 1 ;
    defparam fifo_4_3.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_4_3 (.DI0(Data[4]), .DI1(Data[12]), .DI2(Data[20]), .DI3(Data[28]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_4_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_5_2.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_5_2.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_5_2.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_5_2.AFPOINTER = "0b11111111111111" ;
    defparam fifo_5_2.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_5_2.AEPOINTER = "0b11111111111111" ;
    defparam fifo_5_2.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_5_2.GSR = "DISABLED" ;
    defparam fifo_5_2.RESETMODE = "ASYNC" ;
    defparam fifo_5_2.REGMODE = "NOREG" ;
    defparam fifo_5_2.CSDECODE_R = "0b11" ;
    defparam fifo_5_2.CSDECODE_W = "0b11" ;
    defparam fifo_5_2.DATA_WIDTH_R = 1 ;
    defparam fifo_5_2.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_5_2 (.DI0(Data[5]), .DI1(Data[13]), .DI2(Data[21]), .DI3(Data[29]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_5_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_6_1.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_6_1.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_6_1.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_6_1.AFPOINTER = "0b11111111111111" ;
    defparam fifo_6_1.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_6_1.AEPOINTER = "0b11111111111111" ;
    defparam fifo_6_1.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_6_1.GSR = "DISABLED" ;
    defparam fifo_6_1.RESETMODE = "ASYNC" ;
    defparam fifo_6_1.REGMODE = "NOREG" ;
    defparam fifo_6_1.CSDECODE_R = "0b11" ;
    defparam fifo_6_1.CSDECODE_W = "0b11" ;
    defparam fifo_6_1.DATA_WIDTH_R = 1 ;
    defparam fifo_6_1.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_6_1 (.DI0(Data[6]), .DI1(Data[14]), .DI2(Data[22]), .DI3(Data[30]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_6_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    defparam fifo_7_0.FULLPOINTER1 = "0b00000000000000" ;
    defparam fifo_7_0.FULLPOINTER = "0b11111111111111" ;
    defparam fifo_7_0.AFPOINTER1 = "0b00000000000000" ;
    defparam fifo_7_0.AFPOINTER = "0b11111111111111" ;
    defparam fifo_7_0.AEPOINTER1 = "0b00000000000000" ;
    defparam fifo_7_0.AEPOINTER = "0b11111111111111" ;
    defparam fifo_7_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam fifo_7_0.GSR = "DISABLED" ;
    defparam fifo_7_0.RESETMODE = "ASYNC" ;
    defparam fifo_7_0.REGMODE = "NOREG" ;
    defparam fifo_7_0.CSDECODE_R = "0b11" ;
    defparam fifo_7_0.CSDECODE_W = "0b11" ;
    defparam fifo_7_0.DATA_WIDTH_R = 1 ;
    defparam fifo_7_0.DATA_WIDTH_W = 4 ;
    FIFO8KB fifo_7_0 (.DI0(Data[7]), .DI1(Data[15]), .DI2(Data[23]), .DI3(Data[31]), 
        .DI4(scuba_vlo), .DI5(scuba_vlo), .DI6(scuba_vlo), .DI7(scuba_vlo), 
        .DI8(scuba_vlo), .DI9(scuba_vlo), .DI10(scuba_vlo), .DI11(scuba_vlo), 
        .DI12(scuba_vlo), .DI13(scuba_vlo), .DI14(scuba_vlo), .DI15(scuba_vlo), 
        .DI16(scuba_vlo), .DI17(scuba_vlo), .CSW0(scuba_vhi), .CSW1(fifo_fwe1), 
        .CSR0(scuba_vhi), .CSR1(fifo_fre1), .FULLI(Full_int), .EMPTYI(Empty_int), 
        .WE(WrEn), .RE(RdEn), .ORE(RdEn), .CLKW(WrClock), .CLKR(RdClock), 
        .RST(Reset), .RPRST(RPReset), .DO0(Q_7_m1), .DO1(), .DO2(), .DO3(), 
        .DO4(), .DO5(), .DO6(), .DO7(), .DO8(), .DO9(), .DO10(), .DO11(), 
        .DO12(), .DO13(), .DO14(), .DO15(), .DO16(), .DO17(), .EF(), .AEF(), 
        .AFF(), .FF());

    FD1P3BX FF_6 (.D(fifo_fwe1), .SP(fifo_wei), .CK(WrClock), .PD(Reset), 
        .Q(fifo_fwe0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(fifo_fwe0), .SP(fifo_wei), .CK(WrClock), .CD(Reset), 
        .Q(fifo_fwe1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(ififo_reiring0), .SP(fifo_rei), .CK(RdClock), .CD(Reset), 
        .Q(fifo_reiring0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(ififo_reiring1), .SP(fifo_rei), .CK(RdClock), .CD(Reset), 
        .Q(fifo_reiring1))
             /* synthesis GSR="ENABLED" */;

    FD1P3BX FF_2 (.D(fifo_fre1), .SP(rfifo_rei_tg), .CK(RdClock), .PD(rRst), 
        .Q(fifo_fre0))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(fifo_fre0), .SP(rfifo_rei_tg), .CK(RdClock), .CD(rRst), 
        .Q(fifo_fre1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(fifo_fre1), .SP(fifo_rei), .CK(RdClock), .CD(rRst), 
        .Q(fiforsel))
             /* synthesis GSR="ENABLED" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B fifo_reirs_cia (.A0(scuba_vlo), .A1(scuba_vhi), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(fifo_reirs_ci), .S0(), .S1());

    CU2 fifo_reirs_0 (.CI(fifo_reirs_ci), .PC0(fifo_reiring0), .PC1(fifo_reiring1), 
        .CO(co0), .NC0(ififo_reiring0), .NC1(ififo_reiring1));

    MUX21 mux_7 (.D0(Q_m0), .D1(Q_m1), .SD(fiforsel), .Z(Q[0]));

    MUX21 mux_6 (.D0(Q_1_m0), .D1(Q_1_m1), .SD(fiforsel), .Z(Q[1]));

    MUX21 mux_5 (.D0(Q_2_m0), .D1(Q_2_m1), .SD(fiforsel), .Z(Q[2]));

    MUX21 mux_4 (.D0(Q_3_m0), .D1(Q_3_m1), .SD(fiforsel), .Z(Q[3]));

    MUX21 mux_3 (.D0(Q_4_m0), .D1(Q_4_m1), .SD(fiforsel), .Z(Q[4]));

    MUX21 mux_2 (.D0(Q_5_m0), .D1(Q_5_m1), .SD(fiforsel), .Z(Q[5]));

    MUX21 mux_1 (.D0(Q_6_m0), .D1(Q_6_m1), .SD(fiforsel), .Z(Q[6]));

    MUX21 mux_0 (.D0(Q_7_m0), .D1(Q_7_m1), .SD(fiforsel), .Z(Q[7]));

    assign Empty = Empty_int;
    assign Full = Full_int;


    // exemplar begin
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
